### ISSUE TITLE
Basic FC Filter

### ISSUE THREAD

**Issue by WELLlabs** [WELLlabs/JaltolAPI#2]
in ee_core.py file,

create a dataclass for basic FeatureCollection filtering,

aim of the class is to return filter object that holds the conditions, which in turn will be used to filter the FeatureCollection.

Input: 
{'state': state_name, 'district': district_name, 'subdistrict': subD_name, 'village_na': vill_name}

- [ ] take the input dict, convert it into a list of equal Filter object with the key, value pair
- [ ] method to return ee.Filter.And object for the above

**Comment by WELLlabs** [comment]
input need not be dict, it can be a tuple too. depends on the schema of info from frontend.

**Comment by balakumaran247** [comment]
Archiving this
