### ISSUE TITLE
ImageCollection Filter

### ISSUE THREAD

**Issue by WELLlabs** [WELLlabs/JaltolAPI#3]
in ee_core.py file,

create a dataclass for ImageCollection filtering,

aim of the class is to return filter object that holds the conditions, which in turn will be used to filter the ImageCollection.

input:
start_date, end_date, bounds, list of dict (or tuple) with key, value pair for the conditions

- [ ] take the list of other conditions and convert it into list of ee.Filter.eq or ee.Filter.lte or ee.Filter.gte objects
- [ ] method to return ee.Filter.And object for all conditions

**Comment by balakumaran247** [comment]
Archiving this
