### ISSUE TITLE
Setting up database on AWS

### ISSUE THREAD

**Issue by anmolsingh0219** [WELLlabs/JaltolAPI#4]
Setting up database on AWS

Steps implemented in Order (30-07-24)

- Setup a postgresql Database RDS Database AWS
- Connected it to local instance using postgresql library 
- Uploaded data in the format with primary keys and secondary keys 
- Updated Django Database Connections in Settings.py 
- Created Models.py, Serializers.py and updated views.py 

Current State

- Data is accessible through the cmd interface after connecting it to the server using the AWS provided host link 
-  Data is not accessibile through the django setup backend

**Comment by bprashanth** [comment]
@anmolsingh0219 let's try the following 2 experiments to try and scope the bug. 

1. From the ec2 instance running your django app, execute 
```shell
$ docker run -it --rm postgres psql -h jaltoldatabase-1.cnyqeok8kne6.ap-south-1.rds.amazonaws.com -U admindatabase -d postgres -p 5432
```

2. If that works, try deploying a very basic django app. 

Say something that writes a timestamp to the db everytime you visit `/`, and reads it back to print on the screen. 
```python
# myproject/models.py
from django.db import models

class Visit(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Timestamp")

    def __str__(self):
        return f"Visit at {self.timestamp}"

# myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.http import HttpResponse 
from .models import Visit


def hello_world(request):
    Visit.objects.create()
    recent_visit = Visit.objects.latest('timestamp')
    return HttpResponse(f"Hello, world! {recent_visit.timestamp}")


urlpatterns = [
    path('', hello_world),
]
```
Run that django project in docker the same way, maybe something like 
```shell
$ docker build -t my_django_app .
$ docker run --name my_django -p 8000:8000 -v $(pwd):/app -d my_django_app
$ docker exec -it my_django python manage.py migrate
...
```
That is 90% real code, 10% pseudocode.
If it's confusing lmk and ill upload my test project. 

Make sure your settings.py has the same info in (1) 

Depending on which one of those fails, we'll know how to proceed.

**Comment by bprashanth** [comment]
RDS works. 
* standalone script using django models to populate file based json data into db

**Comment by bprashanth** [comment]
Can you close this issue?
